namespace AiSdlc.ModelProviders;

public sealed class FakeModelProvider : IModelProvider
{
    private readonly ModelProviderOptions _options;

    public FakeModelProvider(ModelProviderOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        _options = options;
    }

    public string ProviderName => _options.ProviderName;

    public Task<ModelResponse> CompleteAsync(ModelRequest request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        cancellationToken.ThrowIfCancellationRequested();

        var tokenLimit = request.MaxTokens ?? _options.DefaultMaxTokens;

        return Task.FromResult(new ModelResponse
        {
            ProviderName = _options.ProviderName,
            ModelName = _options.ModelName,
            ResponseText = $"[{request.AgentName}] {request.TaskType}: deterministic response generated by {_options.ProviderName}.",
            Usage = new Dictionary<string, object>
            {
                ["input_document_count"] = request.ContextDocuments.Count,
                ["max_tokens"] = tokenLimit
            },
            WasTruncated = false,
            Warnings = request.RequiredOutputSchema is null
                ? new List<string>()
                : new List<string> { "Schema enforcement is not implemented by the fake provider." }
        });
    }
}
